<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151012/1-151012201252.jpg ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/151012/1-151012201252.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="790";
$z[2]=Array("img"," /uploads/allimg/151012/1-151012201255.jpg ",243,391);
$z[2][4]['ddimg']="/uploads/allimg/151012/1-151012201255.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="790";
$z[3]=Array("img"," /uploads/allimg/151012/1-151012201258.jpg ",393,541);
$z[3][4]['ddimg']="/uploads/allimg/151012/1-151012201258.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="790";

?>