<a href="[field:arcurl/]">
    <div class="child"><img class="childImg" src="[field:picname/]" />
      <div class="childHide">
        <div class="childTag">
          <div class="childSub"></div>
        </div>
        <div class="childContent">
          <p class="title">[field:title/]</p>
          <p class="info">www.xunmoban.com</p>
        </div>
        <img class="childPointer" src="public/images/project/hidePointer.png"></div>
    </div>
    </a>