<div class="child">
        <div class="childImg"><img src="[field:picname/]" /></div>
        <div class="childInfo">
          <p class="datetime">[field:pubdate function="MyDate('Y.m.d',@me)"/]</p>
          <p class="title">[field:title/]</p>
          <p class="info">[field:infos/]…</p>
          <a href="[field:arcurl/]">
          <div class="childBtn"><span>详细信息</span></div>
          </a></div>
      </div>