<div class="child" id="jobChild20">
        <p class="name">[field:title/]</p>
        <p class="nameEn">[field:infos/]…</p>
        <div class="department">部门:[field:bumen/]<span class="sub">|</span>招聘人数:<span class="redSpan">[field:renshu/]人</span></div>
        <div class="childPointer"></div>
        <div class="childContent">
          <p>任职要求：</p>
          [field:body/]
        </div>
      </div>