
<field:xingming itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:gsmc itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:gsmc>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:xmzt itemname="项目主题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xmzt>

<field:neirong itemname="具体内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:neirong>
