<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",952,987);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1052,1071);
$z[3][4]['name']="title";
$z[4]=Array("field","",1103,1123);
$z[4][4]['name']="writer";
$z[5]=Array("field","",1134,1186);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("field","",1319,1337);
$z[6][4]['name']="body";
$z[7]=Array("field","",1460,1478);
$z[7][4]['name']="body";
$z[8]=Array("productimagelist","\r\n	<img alt=\"[field:text/]\" src=\"[field:imgsrc/]\" style=\"height:791px; width:1200px\" title=\"[field:text/]\" /><br />\r\n	",1510,1675);
$z[9]=Array("include","",1744,1781);
$z[9][4]['filename']="footer.htm";

?>