<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",955,990);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1055,1074);
$z[3][4]['name']="title";
$z[4]=Array("field","",1106,1126);
$z[4][4]['name']="writer";
$z[5]=Array("field","",1137,1189);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("field","",1294,1312);
$z[6][4]['name']="body";
$z[7]=Array("productimagelist","\r\n	<img alt=\"[field:text/]\" src=\"[field:imgsrc/]\" style=\"height:791px; width:1200px\" title=\"[field:text/]\" /><br />\r\n	",1344,1509);
$z[8]=Array("type","<a href=\"[field:typelink /]\"><div class=\"mainFootBtn\">返回列表</div></a>",1628,1744);
$z[8][4]['typeid']="0";
$z[8][4]['row']="1";
$z[9]=Array("arclist","\r\n  <a href=\"[field:arcurl/]\">\r\n    <div class=\"child\"><img class=\"childImg\" src=\"[field:picname/]\" />\r\n      <div class=\"childHide\">\r\n        <div class=\"childTag\">\r\n          <p>VI</p>\r\n          <p>DESIGN</p>\r\n          <div class=\"childSub\"></div>\r\n        </div>\r\n        <div class=\"childContent\">\r\n          <p class=\"title\">[field:title/]</p>\r\n          <p class=\"info\">www.xunmoban.com</p>\r\n        </div>\r\n        <img class=\"childPointer\" src=\"/Public/images/project/hidePointer.png\"></div>\r\n    </div>\r\n    </a>\r\n	",2148,2722);
$z[9][4]['row']="5";
$z[9][4]['typeid']="2";
$z[10]=Array("include","",2779,2816);
$z[10][4]['filename']="footer.htm";

?>