<a href="[field:arcurl/]">
        <div class="child">
          <div class="childTime">
            <p class="timeMonth">[field:pubdate function="MyDate('Y-m',@me)"/]</p>
            <p class="timeDay">[field:pubdate function="MyDate('d',@me)"/]</p>
          </div>
          <div class="childInfo">
            <p class="title">[field:title/]</p>
            <p class="info">[field:infos/]…</p>
          </div>
        </div>
        </a>