<?php
$z[0]=Array("field","(@me==\"\")? @me=\"   class='on'  \":@me=\"\";",253,343);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n	  <a href=\"[field:typeurl/]\"><li>[field:typename/]</li></a>\r\n	  ",364,560);
$z[1][4]['row']="10";
$z[1][4]['type']="top";
$z[1][4]['col']="1";
$z[1][4]['currentstyle']="<a href='~typelink~'><li class='on'>~typename~</li></a>";

?>