<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1128,1163);
$z[2][4]['filename']="head.htm";
$z[3]=Array("arclist","\r\n	  <a href=\"[field:arcurl/]\">\r\n        <div class=\"child\">\r\n          <p class=\"childTitle\">[field:title/]</p>\r\n          <p class=\"childTitleEn\">加入我们吧</p>\r\n          <div class=\"childSub\"></div>\r\n          <p class=\"childMun\">招聘人数: [field:renshu/]人</p>\r\n        </div>\r\n        </a>\r\n		",2159,2545);
$z[3][4]['typeid']="8";
$z[3][4]['row']="4";
$z[3][4]['titlelen']="20";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("include","",6287,6324);
$z[4][4]['filename']="footer.htm";

?>