<?php
$z[0]=Array("global","",264,290);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",921,956);
$z[1][4]['filename']="head.htm";
$z[2]=Array("arclist"," <a href=\"[field:arcurl/]\">\r\n  <div class=\"child\"><img class=\"childImg\" src=\"[field:picname/]\" />\r\n    <div class=\"childHide\">\r\n      <div class=\"childTag\">\r\n        <div class=\"childSub\"></div>\r\n      </div>\r\n      <div class=\"childContent\">\r\n        <p class=\"title\">[field:title/]</p>\r\n        <p class=\"info\">www.xunmoban.com</p>\r\n      </div>\r\n      <img class=\"childPointer\" src=\"public/images/project/hidePointer.png\"></div>\r\n  </div>\r\n  </a> ",4416,4945);
$z[2][4]['typeid']="2";
$z[2][4]['row']="10";
$z[2][4]['titlelen']="20";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist"," <a href=\"#\"><img src=\"[field:picname/]\" alt=\"\" title=\"\" /></a> ",5259,5410);
$z[3][4]['typeid']="9";
$z[3][4]['row']="10";
$z[3][4]['titlelen']="20";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist"," <a href=\"[field:arcurl/]\">\r\n        <div class=\"child\">\r\n          <div class=\"childTime\">\r\n            <p class=\"timeMonth\">[field:pubdate function=\"MyDate('Y-m',@me)\"/]</p>\r\n            <p class=\"timeDay\">[field:pubdate function=\"MyDate('d',@me)\"/]</p>\r\n          </div>\r\n          <div class=\"childInfo\">\r\n            <p class=\"title\">[field:title/]</p>\r\n            <p class=\"info\">[field:infos/]…</p>\r\n          </div>\r\n        </div>\r\n        </a> ",7893,8446);
$z[4][4]['typeid']="7";
$z[4][4]['row']="3";
$z[4][4]['titlelen']="20";
$z[4][4]['infolen']="150";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("include","",8778,8815);
$z[5][4]['filename']="footer.htm";

?>