<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",949,984);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n   <a href=\"#\"> <div class=\"child\"><img src=\"[field:picname/]\" alt=\"\" title=\"\" /></div></a>\r\n   ",1552,1687);
$z[3][4]['pagesize']="28";
$z[4]=Array("include","",1745,1782);
$z[4][4]['filename']="footer.htm";

?>