<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",944,979);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n	  <div class=\"child\" id=\"jobChild20\">\r\n        <p class=\"name\">[field:title/]</p>\r\n        <p class=\"nameEn\">[field:infos/]…</p>\r\n        <div class=\"department\">部门:[field:bumen/]<span class=\"sub\">|</span>招聘人数:<span class=\"redSpan\">[field:renshu/]人</span></div>\r\n        <div class=\"childPointer\"></div>\r\n        <div class=\"childContent\">\r\n          <p>任职要求：</p>\r\n          [field:body/]\r\n        </div>\r\n      </div>\r\n	  ",1590,2091);
$z[3][4]['pagesize']="5";
$z[3][4]['infolen']="80";
$z[4]=Array("include","",2898,2935);
$z[4][4]['filename']="footer.htm";

?>