<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",945,980);
$z[2][4]['filename']="head.htm";
$z[3]=Array("list","\r\n	<a href=\"#\">\r\n      <div class=\"child\">\r\n        <div class=\"childImg\"><img src=\"[field:picname/]\" width=\"247px\" />\r\n          <div class=\"childImgMsg\">\r\n            <p>[field:infos/]…</p>\r\n          </div>\r\n        </div>\r\n        <p class=\"title\">[field:title/]</p>\r\n        <div class=\"sub\"></div>\r\n        <p class=\"info\">团队成员</p>\r\n      </div>\r\n      </a>\r\n	  ",1597,2011);
$z[3][4]['pagesize']="9";
$z[4]=Array("include","",2079,2116);
$z[4][4]['filename']="footer.htm";

?>