<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1128,1163);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n  <a href=\"[field:typeurl/]\"><div class=\"child\">[field:typename/]</div></a>\r\n  ",1677,1815);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("list","\r\n  <a href=\"[field:arcurl/]\">\r\n    <div class=\"child\"><img class=\"childImg\" src=\"[field:picname/]\" />\r\n      <div class=\"childHide\">\r\n        <div class=\"childTag\">\r\n          <div class=\"childSub\"></div>\r\n        </div>\r\n        <div class=\"childContent\">\r\n          <p class=\"title\">[field:title/]</p>\r\n          <p class=\"info\">www.xunmoban.com</p>\r\n        </div>\r\n        <img class=\"childPointer\" src=\"/public/images/project/hidePointer.png\"></div>\r\n    </div>\r\n    </a>\r\n	",1854,2368);
$z[4][4]['pagesize']="10";
$z[5]=Array("include","",2509,2546);
$z[5][4]['filename']="footer.htm";

?>