<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",945,980);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","\r\n  <a href=\"[field:typeurl/]\"><div class=\"child\">[field:typename/]</div></a>\r\n  ",1492,1630);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[4]=Array("list","\r\n	  <div class=\"child\">\r\n        <div class=\"childImg\"><img src=\"[field:picname/]\" /></div>\r\n        <div class=\"childInfo\">\r\n          <p class=\"datetime\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</p>\r\n          <p class=\"title\">[field:title/]</p>\r\n          <p class=\"info\">[field:infos/]…</p>\r\n          <a href=\"[field:arcurl/]\">\r\n          <div class=\"childBtn\"><span>详细信息</span></div>\r\n          </a></div>\r\n      </div>\r\n	  ",1699,2198);
$z[4][4]['pagesize']="10";
$z[4][4]['infolen']="400";
$z[5]=Array("include","",2268,2305);
$z[5][4]['filename']="footer.htm";

?>