<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1132,1167);
$z[2][4]['filename']="head.htm";
$z[3]=Array("arclist","\r\n		<a href=\"#\"><img src=\"[field:picname/]\" alt=\"\" title=\"\" /></a>\r\n		",9327,9446);
$z[3][4]['row']="10";
$z[3][4]['typeid']="9";
$z[4]=Array("include","",9667,9704);
$z[4][4]['filename']="footer.htm";

?>